package util;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

/**
 *
 * @author yongc
 */
public class Config {
    private static Map<String,String> config = new HashMap();
    private final static File configFile = new File("./config.txt");
    
    
    public Config(){
        try {
            if (configFile.createNewFile()){
                //init config file
                writeToFile("#This is default config auto-generated by System\n\ndatabase=mysql");
                storeToVar();
            }else{
                //store into config variable
                storeToVar();
            }
        } catch (IOException ex) {}
    }
    
    public static String get(String key){
        return config.get(key);
    }
    
    public static boolean set(String key,String value){
        config.put(key, value);
        String data = "";
        
        try{
        Scanner scan = new Scanner(configFile);
        while (scan.hasNextLine()){
            String temp = scan.nextLine();
            if(temp.equals("\n")){
                data += "\n";
            }else if (temp.startsWith("#")){
                data += temp + "\n";
            }else{
                String[] tempkey = temp.split(":");
                data += tempkey[0] + ":";
                data += get(tempkey[0]) + "\n";
            }
        }
        }catch (FileNotFoundException ex){
        }

        return writeToFile(data);
    }
    
    private void storeToVar(){
        try{
            Scanner scan = new Scanner(configFile);
            while (scan.hasNextLine()){
                String data = scan.nextLine();
                if(data.equals("\n")){
                    System.out.println("no data");
                }else if (!data.startsWith("#")){
                    String[] key = data.split(":");
                    config.put(key[0], key[1]);
                }
            }
        }catch (FileNotFoundException ex){
        }
    }
    
    private static boolean writeToFile(String data){
        try{
            FileWriter writer = new FileWriter(configFile);
            writer.write(data);
            writer.close();
            return true;
        }catch(IOException ex){
        }
        return false;
    }
}
