package util;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

/**
 *
 * @author yongc
 */
public class Config {
    private Map<String,String> config = new HashMap();
    private final File configfile = new File("./config.txt");
    private Scanner scan;
    
    
    public Config() throws FileNotFoundException, IOException{
        if (configfile.createNewFile()){
            //init config file
            writeToFile("#This is default config auto-generated by System\n\ndatabase=mysql");
            storeToVar();
        }else{
            //store into config variable
            storeToVar();
        }
    }
    
    public String get(String key){
        return config.get(key);
    }
    
    public boolean set(String key,String value){
        config.put(key, value);
        String data = "";
        for (Map.Entry<String,String> entry:config.entrySet()){
            data += entry.toString();
            data += "\n";
        }
        return writeToFile(data);
    }
    
    private void storeToVar() throws FileNotFoundException{
        Scanner scan = new Scanner(configfile);
        while (scan.hasNextLine()){
            String data = scan.nextLine();
            if (!data.startsWith("#")){
                String[] key = data.split(":");
                config.put(key[0], key[1]);
            }
        }
    }
    
    private boolean writeToFile(String data){
        try{
            FileWriter writer = new FileWriter(configfile);
            writer.write(data);
            writer.close();
            return true;
        }catch(IOException ex){
        }
        return false;
    }
}
